import 'package:flutter/material.dart';
import 'package:provider/provider.dart';

import 'token_storage.dart';

class AppLanguage extends ChangeNotifier {
  // Holds current language code and notifies listeners on change.
  AppLanguage({String initialCode = 'en'}) : _code = initialCode;

  String _code;

  String get code => _code;

  Future<void> loadFromStorage() async {
    final profile = await const TokenStorage().readUserProfile();
    final preferred = profile?['preferred_language']?.toString();
    setLanguage(preferred);
  }

  void setLanguage(String? languageCode) {
    if (languageCode == null || languageCode.isEmpty) {
      return;
    }
    if (!AppLocalizations.supportedLanguages.contains(languageCode)) {
      return;
    }
    if (_code == languageCode) {
      return;
    }
    _code = languageCode;
    notifyListeners();
  }
}

class AppLocalizations {
  static const String fallbackLanguage = 'en';
  static const Set<String> supportedLanguages = {
    'en',
    'hi',
    'ta',
    'te',
    'kn',
    'ml',
  };

  // Localized strings keyed by language code.
  static const Map<String, Map<String, String>> _strings = {
    'en': {
      'AgroScan': 'AgroScan',
      'Sign in': 'Sign in',
      'Sign in to continue': 'Sign in to continue',
      'Email': 'Email',
      'Password': 'Password',
      'Password is required.': 'Password is required.',
      'Password must be at least 6 characters.':
          'Password must be at least 6 characters.',
      'Login': 'Login',
      'Forgot password?': 'Forgot password?',
      'New here?': 'New here?',
      'Create account': 'Create account',
      'Login successful.': 'Login successful.',
      'Create account title': 'Create account',
      'Join the community': 'Join the community',
      'GPS helps personalize your reports':
          'GPS helps personalize your reports',
      'Full name': 'Full name',
      'Name is required.': 'Name is required.',
      'Email is required.': 'Email is required.',
      'Code': 'Code',
      'Phone': 'Phone',
      'Phone is required.': 'Phone is required.',
      'Preferred language': 'Preferred language',
      'Address': 'Address',
      'Address is required.': 'Address is required.',
      'Register': 'Register',
      'Registration complete.': 'Registration complete.',
      'Location will be captured automatically.':
          'Location will be captured automatically.',
      'Location: {lat}, {lng}': 'Location: {lat}, {lng}',
      'Reset password': 'Reset password',
      'Forgot your password?': 'Forgot your password?',
      'We will send a reset code': 'We will send a reset code',
      'Email or phone': 'Email or phone',
      'Email or phone is required.': 'Email or phone is required.',
      'Send reset code': 'Send reset code',
      'Enter the OTP sent to your email.': 'Enter the OTP sent to your email.',
      'OTP': 'OTP',
      'OTP is required.': 'OTP is required.',
      'New password': 'New password',
      'New password is required.': 'New password is required.',
      'Reset password button': 'Reset password',
      'If the account exists, a reset code will be sent.':
          'If the account exists, a reset code will be sent.',
      'Password reset successful. You can log in now.':
          'Password reset successful. You can log in now.',
      'Something went wrong. Please try again.':
          'Something went wrong. Please try again.',
      'Profile': 'Profile',
      'Personal details': 'Personal details',
      'Name': 'Name',
      'Location will be updated using GPS when you save.':
          'Location will be updated using GPS when you save.',
      'Update profile': 'Update profile',
      'Profile updated.': 'Profile updated.',
      'Missing access token.': 'Missing access token.',
      'Field dashboard': 'Field dashboard',
      'Refresh': 'Refresh',
      'Notifications': 'Notifications',
      'Online': 'Online',
      'Offline': 'Offline',
      'Profile menu': 'Profile',
      'Logout': 'Logout',
      'Welcome, {name}': 'Welcome, {name}',
      'Current weather': 'Current weather',
      'Live conditions near your farm': 'Live conditions near your farm',
      'Weather data unavailable.': 'Weather data unavailable.',
      'Feels {value} C': 'Feels {value} C',
      'Humidity {value}%': 'Humidity {value}%',
      'Wind {value} kph': 'Wind {value} kph',
      'History analytics': 'History analytics',
      'Trends from your recent scans': 'Trends from your recent scans',
      'Analytics data unavailable.': 'Analytics data unavailable.',
      'History records': 'History records',
      'Download or remove past reports': 'Download or remove past reports',
      'Filter by crop': 'Filter by crop',
      'All crops': 'All crops',
      'No history yet.': 'No history yet.',
      'Scan crop': 'Scan crop',
      'Total diagnoses': 'Total diagnoses',
      'Low': 'Low',
      'Medium': 'Medium',
      'High': 'High',
      'Healthy': 'Healthy',
      'Crop: {crop}': 'Crop: {crop}',
      'Date: {date}': 'Date: {date}',
      'Unknown crop': 'Unknown crop',
      'Report': 'Report',
      'Report saved: {path}': 'Report saved: {path}',
      'Delete': 'Delete',
      'No notifications yet.': 'No notifications yet.',
      'Notifications unavailable.': 'Notifications unavailable.',
      'Please log in to view notifications.':
          'Please log in to view notifications.',
      'Notification': 'Notification',
      'NEW': 'NEW',
      'Choose crop': 'Choose crop',
      'Gallery image': 'Gallery image',
      'Gallery video': 'Gallery video',
      'Camera image': 'Camera image',
      'Camera video': 'Camera video',
      'Unable to extract a frame from video.':
          'Unable to extract a frame from video.',
      'Image is blurry': 'Image is blurry',
      'Please retake the image for a clearer result.':
          'Please retake the image for a clearer result.',
      'OK': 'OK',
      'Missing access token. Please log in again.':
          'Missing access token. Please log in again.',
      'Diagnosis result': 'Diagnosis result',
      'Unknown disease': 'Unknown disease',
      'Confidence {value}%': 'Confidence {value}%',
      'Confidence -': 'Confidence -',
      'Boxes {count}': 'Boxes {count}',
      'View remediation': 'View remediation',
      'Image': 'Image',
      'Heatmap': 'Heatmap',
      'Comparison': 'Comparison',
      'Captured': 'Captured',
      'Reference': 'Reference',
      'Remediation guide': 'Remediation guide',
      'Remediation data unavailable.': 'Remediation data unavailable.',
      'No remediation found for {name}.': 'No remediation found for {name}.',
      'No treatment needed': 'No treatment needed',
      'Severity guidance': 'Severity guidance',
      'Affected parts': 'Affected parts',
      'Environmental risk factors': 'Environmental risk factors',
      'Organic treatment': 'Organic treatment',
      'Chemical treatment': 'Chemical treatment',
      'Prevention tips': 'Prevention tips',
      'Keep plants resilient with these steps.':
          'Keep plants resilient with these steps.',
      'Community tips': 'Community tips',
      'Verified': 'Verified',
      'Tips from experienced farmers': 'Tips from experienced farmers',
      'Companion plants': 'Companion plants',
      'Plant these nearby for natural protection':
          'Plant these nearby for natural protection',
      'When to seek expert': 'When to seek expert',
      'Expected results': 'Expected results',
      'Safety warnings': 'Safety warnings',
      'Dosage {value}': 'Dosage {value}',
      'Frequency {value}': 'Frequency {value}',
      'Cost {value}': 'Cost {value}',
      'Crop image': 'Crop image',
      'The AI could not identify this disease with certainty. Please consult an agricultural expert for an accurate diagnosis.':
          'The AI could not identify this disease with certainty. Please consult an agricultural expert for an accurate diagnosis.',
      'Simple Mode': 'Simple Mode',
      'Convert technical terms to farmer-friendly words':
          'Convert technical terms to farmer-friendly words',
      'Example: "fungicide" → "fungus medicine"':
          'Example: "fungicide" → "fungus medicine"',
      
      // Chatbot strings
      'AI Assistant': 'AI Assistant',
      'AI Farm Assistant': 'AI Farm Assistant',
      'Type your message...': 'Type your message...',
      'Chat history cleared': 'Chat history cleared',
      'Failed to clear chat history': 'Failed to clear chat history',
      'Clear chat': 'Clear chat',
      'Sorry, I\'m having trouble right now. Please try again later.':
          'Sorry, I\'m having trouble right now. Please try again later.',
    },
    'hi': {
      'AgroScan': 'AgroScan',
      'Sign in': 'साइन इन',
      'Sign in to continue': 'जारी रखने के लिए साइन इन करें',
      'Email': 'ईमेल',
      'Password': 'पासवर्ड',
      'Password is required.': 'पासवर्ड आवश्यक है।',
      'Password must be at least 6 characters.':
          'पासवर्ड कम से कम 6 अक्षरों का होना चाहिए।',
      'Login': 'लॉग इन',
      'Forgot password?': 'पासवर्ड भूल गए?',
      'New here?': 'नए हैं?',
      'Create account': 'खाता बनाएं',
      'Login successful.': 'लॉग इन सफल।',
      'Create account title': 'खाता बनाएं',
      'Join the community': 'समुदाय से जुड़ें',
      'GPS helps personalize your reports':
          'GPS आपकी रिपोर्ट को व्यक्तिगत बनाता है',
      'Full name': 'पूरा नाम',
      'Name is required.': 'नाम आवश्यक है।',
      'Email is required.': 'ईमेल आवश्यक है।',
      'Code': 'कोड',
      'Phone': 'फोन',
      'Phone is required.': 'फोन आवश्यक है।',
      'Preferred language': 'पसंदीदा भाषा',
      'Address': 'पता',
      'Address is required.': 'पता आवश्यक है।',
      'Register': 'रजिस्टर',
      'Registration complete.': 'पंजीकरण पूर्ण।',
      'Location will be captured automatically.':
          'स्थान स्वतः कैप्चर किया जाएगा।',
      'Location: {lat}, {lng}': 'स्थान: {lat}, {lng}',
      'Reset password': 'पासवर्ड रीसेट',
      'Forgot your password?': 'पासवर्ड भूल गए?',
      'We will send a reset code': 'हम एक रीसेट कोड भेजेंगे',
      'Email or phone': 'ईमेल या फोन',
      'Email or phone is required.': 'ईमेल या फोन आवश्यक है।',
      'Send reset code': 'रीसेट कोड भेजें',
      'Enter the OTP sent to your email.': 'ईमेल पर भेजा गया OTP दर्ज करें।',
      'OTP': 'OTP',
      'OTP is required.': 'OTP आवश्यक है।',
      'New password': 'नया पासवर्ड',
      'New password is required.': 'नया पासवर्ड आवश्यक है।',
      'Reset password button': 'पासवर्ड रीसेट',
      'If the account exists, a reset code will be sent.':
          'यदि खाता मौजूद है, तो रीसेट कोड भेजा जाएगा।',
      'Password reset successful. You can log in now.':
          'पासवर्ड रीसेट सफल। अब लॉग इन करें।',
      'Profile': 'प्रोफ़ाइल',
      'Personal details': 'व्यक्तिगत विवरण',
      'Name': 'नाम',
      'Location will be updated using GPS when you save.':
          'सेव करने पर GPS से स्थान अपडेट होगा।',
      'Update profile': 'प्रोफ़ाइल अपडेट',
      'Profile updated.': 'प्रोफ़ाइल अपडेट हो गई।',
      'Missing access token.': 'एक्सेस टोकन अनुपलब्ध।',
      'Field dashboard': 'फील्ड डैशबोर्ड',
      'Refresh': 'रिफ्रेश',
      'Notifications': 'सूचनाएं',
      'Online': 'ऑनलाइन',
      'Offline': 'ऑफलाइन',
      'Profile menu': 'प्रोफ़ाइल',
      'Logout': 'लॉग आउट',
      'Welcome, {name}': 'स्वागत है, {name}',
      'Current weather': 'मौजूदा मौसम',
      'Live conditions near your farm': 'आपके खेत के पास लाइव स्थिति',
      'Weather data unavailable.': 'मौसम डेटा उपलब्ध नहीं।',
      'Feels {value} C': 'महसूस {value} C',
      'Humidity {value}%': 'नमी {value}%',
      'Wind {value} kph': 'हवा {value} kph',
      'History analytics': 'इतिहास विश्लेषण',
      'Trends from your recent scans': 'हालिया स्कैन के रुझान',
      'Analytics data unavailable.': 'विश्लेषण डेटा उपलब्ध नहीं।',
      'History records': 'इतिहास रिकॉर्ड',
      'Download or remove past reports': 'पुरानी रिपोर्ट डाउनलोड या हटाएं',
      'Filter by crop': 'फसल के अनुसार फ़िल्टर',
      'All crops': 'सभी फसलें',
      'No history yet.': 'अभी तक कोई इतिहास नहीं।',
      'Scan crop': 'फसल स्कैन करें',
      'Total diagnoses': 'कुल निदान',
      'Low': 'कम',
      'Medium': 'मध्यम',
      'High': 'उच्च',
      'Healthy': 'स्वस्थ',
      'Crop: {crop}': 'फसल: {crop}',
      'Date: {date}': 'तारीख: {date}',
      'Unknown crop': 'अज्ञात फसल',
      'Report': 'रिपोर्ट',
      'Report saved: {path}': 'रिपोर्ट सहेजी गई: {path}',
      'Delete': 'हटाएं',
      'No notifications yet.': 'अभी कोई सूचना नहीं।',
      'Notifications unavailable.': 'सूचनाएं उपलब्ध नहीं।',
      'Please log in to view notifications.':
          'सूचनाएं देखने के लिए लॉग इन करें।',
      'Notification': 'सूचना',
      'NEW': 'नया',
      'Choose crop': 'फसल चुनें',
      'Gallery image': 'गैलरी छवि',
      'Gallery video': 'गैलरी वीडियो',
      'Camera image': 'कैमरा छवि',
      'Camera video': 'कैमरा वीडियो',
      'Unable to extract a frame from video.':
          'वीडियो से फ्रेम निकालने में असमर्थ।',
      'Image is blurry': 'छवि धुंधली है',
      'Please retake the image for a clearer result.':
          'कृपया बेहतर परिणाम के लिए छवि फिर से लें।',
      'OK': 'ठीक है',
      'Missing access token. Please log in again.':
          'एक्सेस टोकन नहीं मिला। फिर से लॉग इन करें।',
      'Diagnosis result': 'निदान परिणाम',
      'Unknown disease': 'अज्ञात रोग',
      'Confidence {value}%': 'विश्वास {value}%',
      'Confidence -': 'विश्वास -',
      'Boxes {count}': 'बॉक्स {count}',
      'View remediation': 'उपचार देखें',
      'Image': 'छवि',
      'Heatmap': 'हीटमैप',
      'Comparison': 'तुलना',
      'Captured': 'कैप्चर किया गया',
      'Reference': 'संदर्भ',
      'Remediation guide': 'उपचार मार्गदर्शिका',
      'Remediation data unavailable.': 'उपचार डेटा उपलब्ध नहीं।',
      'No remediation found for {name}.': '{name} के लिए उपचार नहीं मिला।',
      'No treatment needed': 'उपचार आवश्यक नहीं',
      'Severity guidance': 'गंभीरता मार्गदर्शन',
      'Affected parts': 'प्रभावित भाग',
      'Environmental risk factors': 'पर्यावरणीय जोखिम कारक',
      'Organic treatment': 'जैविक उपचार',
      'Chemical treatment': 'रासायनिक उपचार',
      'Prevention tips': 'रोकथाम सुझाव',
      'Keep plants resilient with these steps.':
          'इन चरणों से पौधों को मजबूत रखें।',
      'Community tips': 'सामुदायिक सुझाव',
      'Verified': 'सत्यापित',
      'Tips from experienced farmers': 'अनुभवी किसानों से टिप्स',
      'Companion plants': 'साथी पौधे',
      'Plant these nearby for natural protection':
          'प्राकृतिक सुरक्षा के लिए इन्हें पास लगाएं',
      'When to seek expert': 'विशेषज्ञ से कब मिलें',
      'Expected results': 'अपेक्षित परिणाम',
      'Safety warnings': 'सुरक्षा चेतावनियां',
      'Dosage {value}': 'खुराक {value}',
      'Frequency {value}': 'आवृत्ति {value}',
      'Cost {value}': 'लागत {value}',
      'Crop image': 'छवि क्रॉप करें',
      'The AI could not identify this disease with certainty. Please consult an agricultural expert for an accurate diagnosis.':
          'AI इस रोग की पहचान निश्चितता से नहीं कर सका। सटीक निदान के लिए किसी कृषि विशेषज्ञ से परामर्श करें।',
      
      // Chatbot strings
      'AI Assistant': 'एआई सहायक',
      'AI Farm Assistant': 'एआई कृषि सहायक',
      'Type your message...': 'अपना संदेश लिखें...',
      'Chat history cleared': 'चैट इतिहास साफ़ किया गया',
      'Failed to clear chat history': 'चैट इतिहास साफ़ करने में विफल',
      'Clear chat': 'चैट साफ़ करें',
      'Sorry, I\'m having trouble right now. Please try again later.':
          'क्षमा करें, मुझे अभी समस्या हो रही है। कृपया बाद में पुनः प्रयास करें।',
    },
    'ta': {
      'AgroScan': 'AgroScan',
      'Sign in': 'உள்நுழை',
      'Sign in to continue': 'தொடர உள்நுழையவும்',
      'Email': 'மின்னஞ்சல்',
      'Password': 'கடவுச்சொல்',
      'Password is required.': 'கடவுச்சொல் தேவை.',
      'Password must be at least 6 characters.':
          'கடவுச்சொல் குறைந்தது 6 எழுத்துகள் இருக்க வேண்டும்.',
      'Login': 'உள்நுழை',
      'Forgot password?': 'கடவுச்சொல் மறந்துவிட்டதா?',
      'New here?': 'புதியவரா?',
      'Create account': 'கணக்கை உருவாக்கவும்',
      'Login successful.': 'உள்நுழைவு வெற்றிகரமாக.',
      'Create account title': 'கணக்கை உருவாக்கவும்',
      'Join the community': 'சமூகத்தில் சேருங்கள்',
      'GPS helps personalize your reports':
          'GPS உங்கள் அறிக்கைகளை தனிப்பயனாக்க உதவும்',
      'Full name': 'முழுப் பெயர்',
      'Name is required.': 'பெயர் தேவை.',
      'Email is required.': 'மின்னஞ்சல் தேவை.',
      'Code': 'குறியீடு',
      'Phone': 'தொலைபேசி',
      'Phone is required.': 'தொலைபேசி தேவை.',
      'Preferred language': 'விருப்ப மொழி',
      'Address': 'முகவரி',
      'Address is required.': 'முகவரி தேவை.',
      'Register': 'பதிவு',
      'Registration complete.': 'பதிவு முடிந்தது.',
      'Location will be captured automatically.':
          'இருப்பிடம் தானாக பெறப்படும்.',
      'Location: {lat}, {lng}': 'இருப்பிடம்: {lat}, {lng}',
      'Reset password': 'கடவுச்சொல்லை மீட்டமை',
      'Forgot your password?': 'கடவுச்சொல் மறந்துவிட்டதா?',
      'We will send a reset code': 'மீட்டமைப்பு குறியீடு அனுப்பப்படும்',
      'Email or phone': 'மின்னஞ்சல் அல்லது தொலைபேசி',
      'Email or phone is required.': 'மின்னஞ்சல் அல்லது தொலைபேசி தேவை.',
      'Send reset code': 'மீட்டமைப்பு குறியீடு அனுப்பு',
      'Enter the OTP sent to your email.':
          'உங்கள் மின்னஞ்சலுக்கு அனுப்பிய OTP ஐ உள்ளிடவும்.',
      'OTP': 'OTP',
      'OTP is required.': 'OTP தேவை.',
      'New password': 'புதிய கடவுச்சொல்',
      'New password is required.': 'புதிய கடவுச்சொல் தேவை.',
      'Reset password button': 'கடவுச்சொல்லை மீட்டமை',
      'If the account exists, a reset code will be sent.':
          'கணக்கு இருந்தால், மீட்டமைப்பு குறியீடு அனுப்பப்படும்.',
      'Password reset successful. You can log in now.':
          'கடவுச்சொல் மீட்டமை வெற்றிகரமாக. இப்போது உள்நுழையலாம்.',
      'Profile': 'சுயவிவரம்',
      'Personal details': 'தனிப்பட்ட விவரங்கள்',
      'Name': 'பெயர்',
      'Location will be updated using GPS when you save.':
          'சேமிக்கும் போது GPS மூலம் இருப்பிடம் புதுப்பிக்கப்படும்.',
      'Update profile': 'சுயவிவரம் புதுப்பிக்க',
      'Profile updated.': 'சுயவிவரம் புதுப்பிக்கப்பட்டது.',
      'Missing access token.': 'அணுகல் டோக்கன் இல்லை.',
      'Field dashboard': 'வயல் டாஷ்போர்டு',
      'Refresh': 'புதுப்பி',
      'Notifications': 'அறிவிப்புகள்',
      'Online': 'ஆன்லைன்',
      'Offline': 'ஆஃப்லைன்',
      'Profile menu': 'சுயவிவரம்',
      'Logout': 'வெளியேறு',
      'Welcome, {name}': 'வரவேற்பு, {name}',
      'Current weather': 'தற்போதைய வானிலை',
      'Live conditions near your farm': 'உங்கள் வயல் அருகிலுள்ள நிலை',
      'Weather data unavailable.': 'வானிலை தரவு கிடைக்கவில்லை.',
      'Feels {value} C': 'உணர்வு {value} C',
      'Humidity {value}%': 'ஈரப்பதம் {value}%',
      'Wind {value} kph': 'காற்று {value} kph',
      'History analytics': 'வரலாறு பகுப்பாய்வு',
      'Trends from your recent scans': 'சமீபத்திய ஸ்கேன் போக்குகள்',
      'Analytics data unavailable.': 'பகுப்பாய்வு தரவு கிடைக்கவில்லை.',
      'History records': 'வரலாறு பதிவுகள்',
      'Download or remove past reports':
          'முந்தைய அறிக்கைகளை பதிவிறக்க அல்லது நீக்கு',
      'Filter by crop': 'பயிர் அடிப்படையில் வடிகட்டு',
      'All crops': 'அனைத்து பயிர்கள்',
      'No history yet.': 'இன்னும் வரலாறு இல்லை.',
      'Scan crop': 'பயிரை ஸ்கேன் செய்யவும்',
      'Total diagnoses': 'மொத்த கண்டறிதல்கள்',
      'Low': 'குறைவு',
      'Medium': 'நடுத்தரம்',
      'High': 'உயரம்',
      'Healthy': 'ஆரோக்கியம்',
      'Crop: {crop}': 'பயிர்: {crop}',
      'Date: {date}': 'தேதி: {date}',
      'Unknown crop': 'அறியப்படாத பயிர்',
      'Report': 'அறிக்கை',
      'Report saved: {path}': 'அறிக்கை சேமிக்கப்பட்டது: {path}',
      'Delete': 'நீக்கு',
      'No notifications yet.': 'இன்னும் அறிவிப்புகள் இல்லை.',
      'Notifications unavailable.': 'அறிவிப்புகள் கிடைக்கவில்லை.',
      'Please log in to view notifications.':
          'அறிவிப்புகளைப் பார்க்க உள்நுழையவும்.',
      'Notification': 'அறிவிப்பு',
      'NEW': 'புதியது',
      'Choose crop': 'பயிரை தேர்வு செய்யவும்',
      'Gallery image': 'காட்சியகம் படம்',
      'Gallery video': 'காட்சியகம் வீடியோ',
      'Camera image': 'கேமரா படம்',
      'Camera video': 'கேமரா வீடியோ',
      'Unable to extract a frame from video.':
          'வீடியோவில் இருந்து ஃப்ரேம் பெற முடியவில்லை.',
      'Image is blurry': 'படம் மங்கலாக உள்ளது',
      'Please retake the image for a clearer result.':
          'மேலும் தெளிவான முடிவுக்காக படத்தை மீண்டும் எடுக்கவும்.',
      'OK': 'சரி',
      'Missing access token. Please log in again.':
          'அணுகல் டோக்கன் இல்லை. மீண்டும் உள்நுழையவும்.',
      'Diagnosis result': 'கண்டறிதல் முடிவு',
      'Unknown disease': 'அறியப்படாத நோய்',
      'Confidence {value}%': 'நம்பகத்தன்மை {value}%',
      'Confidence -': 'நம்பகத்தன்மை -',
      'Boxes {count}': 'பெட்டிகள் {count}',
      'View remediation': 'சிகிச்சையைப் பார்க்க',
      'Image': 'படம்',
      'Heatmap': 'வெப்ப வரைபடம்',
      'Comparison': 'ஒப்பீடு',
      'Captured': 'பிடிக்கப்பட்டது',
      'Reference': 'ஆதாரம்',
      'Remediation guide': 'சிகிச்சை வழிகாட்டி',
      'Remediation data unavailable.': 'சிகிச்சை தரவு கிடைக்கவில்லை.',
      'No remediation found for {name}.': '{name} க்கு சிகிச்சை இல்லை.',
      'No treatment needed': 'சிகிச்சை தேவையில்லை',
      'Severity guidance': 'தீவிரம் வழிகாட்டி',
      'Affected parts': 'பாதிக்கப்பட்ட பகுதிகள்',
      'Environmental risk factors': 'சுற்றுச்சூழல் ஆபத்து காரணிகள்',
      'Organic treatment': 'இயற்கை சிகிச்சை',
      'Chemical treatment': 'ரசாயன சிகிச்சை',
      'Prevention tips': 'தடுப்பு குறிப்புகள்',
      'Keep plants resilient with these steps.':
          'இந்த படிகளால் பயிர்களை வலுப்படுத்தவும்.',
      'Community tips': 'சமுதாய குறிப்புகள்',
      'Verified': 'சரிபார்க்கப்பட்ட',
      'Tips from experienced farmers': 'அனுபவமுள்ள விவசாயிகளின் குறிப்புகள்',
      'Companion plants': 'தோழ தாவரங்கள்',
      'Plant these nearby for natural protection':
          'இயற்கை பாதுகாப்பிற்கு இவற்றை அருகில் நடவும்',
      'When to seek expert': 'எப்போது வல்லுநரிடம் செல்ல வேண்டும்',
      'Expected results': 'எதிர்பார்க்கப்படும் முடிவுகள்',
      'Safety warnings': 'பாதுகாப்பு எச்சரிக்கைகள்',
      'Dosage {value}': 'அளவு {value}',
      'Frequency {value}': 'அடிக்கடி {value}',
      'Cost {value}': 'செலவு {value}',
      'Crop image': 'படத்தை குரைத்தல்',
      'The AI could not identify this disease with certainty. Please consult an agricultural expert for an accurate diagnosis.':
          'AI இந்த நோயை உறுதியாக அடையாளம் காண இயலவில்லை. சரியான நோயறிதலுக்கு விவசாய நிபுணரிடம் ஆலோசிக்கவும்.',
      
      // Chatbot strings
      'AI Assistant': 'AI உதவியாளர்',
      'AI Farm Assistant': 'AI விவசாய உதவியாளர்',
      'Type your message...': 'உங்கள் செய்தியை தட்டச்சு செய்யுங்கள்...',
      'Chat history cleared': 'அரட்டை வரலாறு அழிக்கப்பட்டது',
      'Failed to clear chat history': 'அரட்டை வரலாறு அழிக்க முடியவில்லை',
      'Clear chat': 'அரட்டையை அழி',
      'Sorry, I\'m having trouble right now. Please try again later.':
          'மன்னிக்கவும், எனக்கு இப்போது சிக்கல் உள்ளது. தயவுசெய்து பின்னர் மீண்டும் முயற்சிக்கவும்.',
    },
    'te': {
      'AgroScan': 'AgroScan',
      'Sign in': 'సైన్ ఇన్',
      'Sign in to continue': 'కొనసాగించేందుకు సైన్ ఇన్ చేయండి',
      'Email': 'ఇమెయిల్',
      'Password': 'పాస్వర్డ్',
      'Password is required.': 'పాస్వర్డ్ అవసరం.',
      'Password must be at least 6 characters.':
          'పాస్వర్డ్ కనీసం 6 అక్షరాలు ఉండాలి.',
      'Login': 'లాగిన్',
      'Forgot password?': 'పాస్వర్డ్ మర్చిపోయారా?',
      'New here?': 'కొత్తవారా?',
      'Create account': 'ఖాతా సృష్టించండి',
      'Login successful.': 'లాగిన్ విజయవంతమైంది.',
      'Create account title': 'ఖాతా సృష్టించండి',
      'Join the community': 'సముదాయంలో చేరండి',
      'GPS helps personalize your reports':
          'GPS మీ నివేదికలను వ్యక్తిగతీకరించడానికి సహాయపడుతుంది',
      'Full name': 'పూర్తి పేరు',
      'Name is required.': 'పేరు అవసరం.',
      'Email is required.': 'ఇమెయిల్ అవసరం.',
      'Code': 'కోడ్',
      'Phone': 'ఫోన్',
      'Phone is required.': 'ఫోన్ అవసరం.',
      'Preferred language': 'ప్రాధాన్య భాష',
      'Address': 'చిరునామా',
      'Address is required.': 'చిరునామా అవసరం.',
      'Register': 'నమోదు',
      'Registration complete.': 'నమోదు పూర్తైంది.',
      'Location will be captured automatically.':
          'స్థానం స్వయంచాలకంగా పొందబడుతుంది.',
      'Location: {lat}, {lng}': 'స్థానం: {lat}, {lng}',
      'Reset password': 'పాస్వర్డ్ రీసెట్',
      'Forgot your password?': 'పాస్వర్డ్ మర్చిపోయారా?',
      'We will send a reset code': 'మేము రీసెట్ కోడ్ పంపిస్తాము',
      'Email or phone': 'ఇమెయిల్ లేదా ఫోన్',
      'Email or phone is required.': 'ఇమెయిల్ లేదా ఫోన్ అవసరం.',
      'Send reset code': 'రీసెట్ కోడ్ పంపండి',
      'Enter the OTP sent to your email.':
          'మీ ఇమెయిల్‌కు పంపిన OTP ను నమోదు చేయండి.',
      'OTP': 'OTP',
      'OTP is required.': 'OTP అవసరం.',
      'New password': 'కొత్త పాస్వర్డ్',
      'New password is required.': 'కొత్త పాస్వర్డ్ అవసరం.',
      'Reset password button': 'పాస్వర్డ్ రీసెట్',
      'If the account exists, a reset code will be sent.':
          'ఖాతా ఉంటే, రీసెట్ కోడ్ పంపబడుతుంది.',
      'Password reset successful. You can log in now.':
          'పాస్వర్డ్ రీసెట్ విజయవంతమైంది. ఇప్పుడు లాగిన్ చేయండి.',
      'Profile': 'ప్రొఫైల్',
      'Personal details': 'వ్యక్తిగత వివరాలు',
      'Name': 'పేరు',
      'Location will be updated using GPS when you save.':
          'సేవ్ చేసినప్పుడు GPS ద్వారా స్థానం నవీకరించబడుతుంది.',
      'Update profile': 'ప్రొఫైల్ నవీకరించండి',
      'Profile updated.': 'ప్రొఫైల్ నవీకరించబడింది.',
      'Missing access token.': 'యాక్సెస్ టోకెన్ లేదు.',
      'Field dashboard': 'ఫీల్డ్ డాష్‌బోర్డ్',
      'Refresh': 'రిఫ్రెష్',
      'Notifications': 'నోటిఫికేషన్లు',
      'Online': 'ఆన్‌లైన్',
      'Offline': 'ఆఫ్‌లైన్',
      'Profile menu': 'ప్రొఫైల్',
      'Logout': 'లాగ్ అవుట్',
      'Welcome, {name}': 'స్వాగతం, {name}',
      'Current weather': 'ప్రస్తుత వాతావరణం',
      'Live conditions near your farm': 'మీ పొలం దగ్గర ప్రత్యక్ష పరిస్థితులు',
      'Weather data unavailable.': 'వాతావరణ డేటా అందుబాటులో లేదు.',
      'Feels {value} C': 'అనుభూతి {value} C',
      'Humidity {value}%': 'తేమ {value}%',
      'Wind {value} kph': 'గాలి {value} kph',
      'History analytics': 'చరిత్ర విశ్లేషణ',
      'Trends from your recent scans': 'ఇటీవలి స్కాన్‌ల ధోరణులు',
      'Analytics data unavailable.': 'విశ్లేషణ డేటా అందుబాటులో లేదు.',
      'History records': 'చరిత్ర రికార్డులు',
      'Download or remove past reports':
          'గత నివేదికలను డౌన్‌లోడ్ చేయండి లేదా తొలగించండి',
      'Filter by crop': 'పంట ప్రకారం వడపోసు',
      'All crops': 'అన్ని పంటలు',
      'No history yet.': 'ఇంకా చరిత్ర లేదు.',
      'Scan crop': 'పంట స్కాన్ చేయండి',
      'Total diagnoses': 'మొత్తం నిర్ధారణలు',
      'Low': 'తక్కువ',
      'Medium': 'మధ్యస్థ',
      'High': 'ఎక్కువ',
      'Healthy': 'ఆరోగ్యకరం',
      'Crop: {crop}': 'పంట: {crop}',
      'Date: {date}': 'తేదీ: {date}',
      'Unknown crop': 'తెలియని పంట',
      'Report': 'నివేదిక',
      'Report saved: {path}': 'నివేదిక సేవ్ అయింది: {path}',
      'Delete': 'తొలగించండి',
      'No notifications yet.': 'ఇంకా నోటిఫికేషన్లు లేవు.',
      'Notifications unavailable.': 'నోటిఫికేషన్లు అందుబాటులో లేవు.',
      'Please log in to view notifications.':
          'నోటిఫికేషన్లు చూడడానికి లాగిన్ చేయండి.',
      'Notification': 'నోటిఫికేషన్',
      'NEW': 'కొత్తది',
      'Choose crop': 'పంటను ఎంచుకోండి',
      'Gallery image': 'గ్యాలరీ చిత్రం',
      'Gallery video': 'గ్యాలరీ వీడియో',
      'Camera image': 'కెమెరా చిత్రం',
      'Camera video': 'కెమెరా వీడియో',
      'Unable to extract a frame from video.':
          'వీడియో నుండి ఫ్రేమ్‌ను తీసుకోలేకపోయాము.',
      'Image is blurry': 'చిత్రం మసకగా ఉంది',
      'Please retake the image for a clearer result.':
          'స్పష్టమైన ఫలితానికి దయచేసి చిత్రాన్ని మళ్లీ తీయండి.',
      'OK': 'సరే',
      'Missing access token. Please log in again.':
          'యాక్సెస్ టోకెన్ లేదు. మళ్లీ లాగిన్ చేయండి.',
      'Diagnosis result': 'నిర్ధారణ ఫలితం',
      'Unknown disease': 'తెలియని వ్యాధి',
      'Confidence {value}%': 'నమ్మకం {value}%',
      'Confidence -': 'నమ్మకం -',
      'Boxes {count}': 'బాక్సులు {count}',
      'View remediation': 'చికిత్స చూడండి',
      'Image': 'చిత్రం',
      'Heatmap': 'హీట్‌మ్యాప్',
      'Comparison': 'పోలిక',
      'Captured': 'సేకరించినది',
      'Reference': 'సూచన',
      'Remediation guide': 'చికిత్స మార్గదర్శకం',
      'Remediation data unavailable.': 'చికిత్స డేటా అందుబాటులో లేదు.',
      'No remediation found for {name}.': '{name} కోసం చికిత్స కనబడలేదు.',
      'No treatment needed': 'చికిత్స అవసరం లేదు',
      'Severity guidance': 'తీవ్రత మార్గదర్శకం',
      'Affected parts': 'ప్రభావితమైన భాగాలు',
      'Environmental risk factors': 'పర్యావరణ ప్రమాద కారకాలు',
      'Organic treatment': 'సేంద్రియ చికిత్స',
      'Chemical treatment': 'రసాయన చికిత్స',
      'Prevention tips': 'నిరోధక సూచనలు',
      'Keep plants resilient with these steps.': 'ఈ దశలతో పంటలను బలంగా ఉంచండి.',
      'Community tips': 'సమాజ సూచనలు',
      'Verified': 'ధృవీకరించిన',
      'Tips from experienced farmers': 'అనుభవవంతమైన రైతుల నుండి సూచనలు',
      'Companion plants': 'సహచర్య మొక్కలు',
      'Plant these nearby for natural protection':
          'సహజ సంరక్షణ కోసం ఇవನ్ని సమీపంలో నాటండి',
      'When to seek expert': 'ఎప్పుడు నిపుణుని కలుసుకోవాలి',
      'Expected results': 'ఆశించిన ఫలితాలు',
      'Safety warnings': 'భద్రతా హెచ్చరికలు',
      'Dosage {value}': 'మోతాదు {value}',
      'Frequency {value}': 'తరచుదనం {value}',
      'Cost {value}': 'ఖర్చు {value}',
      'Crop image': 'చిత్రాన్ని క్రాప్ చేయండి',
      'The AI could not identify this disease with certainty. Please consult an agricultural expert for an accurate diagnosis.':
          'AI ఈ వ్యాధిని ఖచ్చితంగా గుర్తించలేకపోయింది. సరైన నిర్ధారణ కోసం వ్యవసాయ నిపుణుని సంప్రదించండి.',
      
      // Chatbot strings
      'AI Assistant': 'AI సహాయకుడు',
      'AI Farm Assistant': 'AI వ్యవసాయ సహాయకుడు',
      'Type your message...': 'మీ సందేశాన్ని టైప్ చేయండి...',
      'Chat history cleared': 'చాట్ చరిత్ర క్లియర్ చేయబడింది',
      'Failed to clear chat history': 'చాట్ చరిత్రను క్లియర్ చేయడంలో విఫలమైంది',
      'Clear chat': 'చాట్ క్లియర్ చేయండి',
      'Sorry, I\'m having trouble right now. Please try again later.':
          'క్షమించండి, నాకు ఇప్పుడు ఇబ్బంది ఉంది. దయచేసి తర్వాత మళ్లీ ప్రయత్నించండి.',
    },
    'kn': {
      'AgroScan': 'AgroScan',
      'Sign in': 'ಸೈನ್ ಇನ್',
      'Sign in to continue': 'ಮುಂದುವರಿಸಲು ಸೈನ್ ಇನ್ ಮಾಡಿ',
      'Email': 'ಇಮೇಲ್',
      'Password': 'ಪಾಸ್‌ವರ್ಡ್',
      'Password is required.': 'ಪಾಸ್‌ವರ್ಡ್ ಅಗತ್ಯ.',
      'Password must be at least 6 characters.':
          'ಪಾಸ್‌ವರ್ಡ್ ಕನಿಷ್ಠ 6 ಅಕ್ಷರಗಳಿರಬೇಕು.',
      'Login': 'ಲಾಗಿನ್',
      'Forgot password?': 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?',
      'New here?': 'ಹೊಸವರಾ?',
      'Create account': 'ಖಾತೆ ರಚಿಸಿ',
      'Login successful.': 'ಲಾಗಿನ್ ಯಶಸ್ವಿ.',
      'Create account title': 'ಖಾತೆ ರಚಿಸಿ',
      'Join the community': 'ಸಮುದಾಯಕ್ಕೆ ಸೇರಿ',
      'GPS helps personalize your reports':
          'GPS ನಿಮ್ಮ ವರದಿಗಳನ್ನು ವೈಯಕ್ತೀಕರಿಸಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ',
      'Full name': 'ಪೂರ್ಣ ಹೆಸರು',
      'Name is required.': 'ಹೆಸರು ಅಗತ್ಯ.',
      'Email is required.': 'ಇಮೇಲ್ ಅಗತ್ಯ.',
      'Code': 'ಕೋಡ್',
      'Phone': 'ಫೋನ್',
      'Phone is required.': 'ಫೋನ್ ಅಗತ್ಯ.',
      'Preferred language': 'ಆದ್ಯತೆಯ ಭಾಷೆ',
      'Address': 'ವಿಳಾಸ',
      'Address is required.': 'ವಿಳಾಸ ಅಗತ್ಯ.',
      'Register': 'ನೋಂದಣಿ',
      'Registration complete.': 'ನೋಂದಣಿ ಪೂರ್ಣವಾಗಿದೆ.',
      'Location will be captured automatically.':
          'ಸ್ಥಳವನ್ನು ಸ್ವಯಂಚಾಲಿತವಾಗಿ ಪಡೆಯಲಾಗುತ್ತದೆ.',
      'Location: {lat}, {lng}': 'ಸ್ಥಳ: {lat}, {lng}',
      'Reset password': 'ಪಾಸ್‌ವರ್ಡ್ ರೀಸೆಟ್',
      'Forgot your password?': 'ಪಾಸ್‌ವರ್ಡ್ ಮರೆತಿರಾ?',
      'We will send a reset code': 'ನಾವು ರೀಸೆಟ್ ಕೋಡ್ ಕಳುಹಿಸುತ್ತೇವೆ',
      'Email or phone': 'ಇಮೇಲ್ ಅಥವಾ ಫೋನ್',
      'Email or phone is required.': 'ಇಮೇಲ್ ಅಥವಾ ಫೋನ್ ಅಗತ್ಯ.',
      'Send reset code': 'ರೀಸೆಟ್ ಕೋಡ್ ಕಳುಹಿಸಿ',
      'Enter the OTP sent to your email.':
          'ನಿಮ್ಮ ಇಮೇಲ್‌ಗೆ ಕಳುಹಿಸಿದ OTP ಅನ್ನು ನಮೂದಿಸಿ.',
      'OTP': 'OTP',
      'OTP is required.': 'OTP ಅಗತ್ಯ.',
      'New password': 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್',
      'New password is required.': 'ಹೊಸ ಪಾಸ್‌ವರ್ಡ್ ಅಗತ್ಯ.',
      'Reset password button': 'ಪಾಸ್‌ವರ್ಡ್ ರೀಸೆಟ್',
      'If the account exists, a reset code will be sent.':
          'ಖಾತೆ ಇದ್ದರೆ, ರೀಸೆಟ್ ಕೋಡ್ ಕಳುಹಿಸಲಾಗುತ್ತದೆ.',
      'Password reset successful. You can log in now.':
          'ಪಾಸ್‌ವರ್ಡ್ ರೀಸೆಟ್ ಯಶಸ್ವಿ. ಈಗ ಲಾಗಿನ್ ಮಾಡಿ.',
      'Profile': 'ಪ್ರೊಫೈಲ್',
      'Personal details': 'ವೈಯಕ್ತಿಕ ವಿವರಗಳು',
      'Name': 'ಹೆಸರು',
      'Location will be updated using GPS when you save.':
          'ಸೇವ್ ಮಾಡಿದಾಗ GPS ಮೂಲಕ ಸ್ಥಳ ಅಪ್ಡೇಟ್ ಆಗುತ್ತದೆ.',
      'Update profile': 'ಪ್ರೊಫೈಲ್ ಅಪ್ಡೇಟ್',
      'Profile updated.': 'ಪ್ರೊಫೈಲ್ ಅಪ್ಡೇಟ್ ಆಗಿದೆ.',
      'Missing access token.': 'ಆಕ್ಸೆಸ್ ಟೋಕನ್ ಇಲ್ಲ.',
      'Field dashboard': 'ಫೀಲ್ಡ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್',
      'Refresh': 'ರಿಫ್ರೆಶ್',
      'Notifications': 'ನೋಟಿಫಿಕೇಷನ್‌ಗಳು',
      'Online': 'ಆನ್ಲೈನ್',
      'Offline': 'ಆಫ್ಲೈನ್',
      'Profile menu': 'ಪ್ರೊಫೈಲ್',
      'Logout': 'ಲಾಗ್ ಔಟ್',
      'Welcome, {name}': 'ಸ್ವಾಗತ, {name}',
      'Current weather': 'ಪ್ರಸ್ತುತ ಹವಾಮಾನ',
      'Live conditions near your farm': 'ನಿಮ್ಮ ಹೊಲದ ಸಮೀಪದ ಸ್ಥಿತಿ',
      'Weather data unavailable.': 'ಹವಾಮಾನ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ.',
      'Feels {value} C': 'ಅನುಭವ {value} C',
      'Humidity {value}%': 'ಆರ್ದ್ರತೆ {value}%',
      'Wind {value} kph': 'ಗಾಳಿ {value} kph',
      'History analytics': 'ಇತಿಹಾಸ ವಿಶ್ಲೇಷಣೆ',
      'Trends from your recent scans': 'ಇತ್ತೀಚಿನ ಸ್ಕ್ಯಾನ್‌ಗಳ ಪ್ರವೃತ್ತಿಗಳು',
      'Analytics data unavailable.': 'ವಿಶ್ಲೇಷಣೆ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ.',
      'History records': 'ಇತಿಹಾಸ ದಾಖಲಗಳು',
      'Download or remove past reports':
          'ಹಿಂದಿನ ವರದಿಗಳನ್ನು ಡೌನ್‌ಲೋಡ್ ಅಥವಾ ಅಳಿಸಿ',
      'Filter by crop': 'ಬೆಳೆಯ ಪ್ರಕಾರ ಫಿಲ್ಟರ್',
      'All crops': 'ಎಲ್ಲಾ ಬೆಳೆಗಳು',
      'No history yet.': 'ಇನ್ನೂ ಇತಿಹಾಸ ಇಲ್ಲ.',
      'Scan crop': 'ಬೆಳೆ ಸ್ಕ್ಯಾನ್ ಮಾಡಿ',
      'Total diagnoses': 'ಒಟ್ಟು ನಿರ್ಣಯಗಳು',
      'Low': 'ಕಡಿಮೆ',
      'Medium': 'ಮಧ್ಯಮ',
      'High': 'ಹೆಚ್ಚು',
      'Healthy': 'ಆರೋಗ್ಯಕರ',
      'Crop: {crop}': 'ಬೆಳೆ: {crop}',
      'Date: {date}': 'ದಿನಾಂಕ: {date}',
      'Unknown crop': 'ಅಜ್ಞಾತ ಬೆಳೆ',
      'Report': 'ವರದಿ',
      'Report saved: {path}': 'ವರದಿ ಉಳಿಸಲಾಗಿದೆ: {path}',
      'Delete': 'ಅಳಿಸಿ',
      'No notifications yet.': 'ಇನ್ನೂ ನೋಟಿಫಿಕೇಷನ್‌ಗಳು ಇಲ್ಲ.',
      'Notifications unavailable.': 'ನೋಟಿಫಿಕೇಷನ್‌ಗಳು ಲಭ್ಯವಿಲ್ಲ.',
      'Please log in to view notifications.':
          'ನೋಟಿಫಿಕೇಷನ್‌ಗಳನ್ನು ನೋಡಲು ಲಾಗಿನ್ ಮಾಡಿ.',
      'Notification': 'ನೋಟಿಫಿಕೇಷನ್',
      'NEW': 'ಹೊಸದು',
      'Choose crop': 'ಬೆಳೆ ಆಯ್ಕೆ ಮಾಡಿ',
      'Gallery image': 'ಗ್ಯಾಲರಿ ಚಿತ್ರ',
      'Gallery video': 'ಗ್ಯಾಲರಿ ವೀಡಿಯೋ',
      'Camera image': 'ಕ್ಯಾಮೆರಾ ಚಿತ್ರ',
      'Camera video': 'ಕ್ಯಾಮೆರಾ ವೀಡಿಯೋ',
      'Unable to extract a frame from video.':
          'ವೀಡಿಯೋದಿಂದ ಫ್ರೇಮ್ ಪಡೆಯಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ.',
      'Image is blurry': 'ಚಿತ್ರ ಮಂಕಾಗಿದೆ',
      'Please retake the image for a clearer result.':
          'ಸ್ಪಷ್ಟವಾದ ಫಲಿತಾಂಶಕ್ಕಾಗಿ ದಯವಿಟ್ಟು ಚಿತ್ರವನ್ನು ಮರುತೆಗೆದುಕೊಳ್ಳಿ.',
      'OK': 'ಸರಿ',
      'Missing access token. Please log in again.':
          'ಆಕ್ಸೆಸ್ ಟೋಕನ್ ಇಲ್ಲ. ಮತ್ತೆ ಲಾಗಿನ್ ಮಾಡಿ.',
      'Diagnosis result': 'ನಿರ್ಣಯ ಫಲಿತಾಂಶ',
      'Unknown disease': 'ಅಜ್ಞಾತ ರೋಗ',
      'Confidence {value}%': 'ವಿಶ್ವಾಸ {value}%',
      'Confidence -': 'ವಿಶ್ವಾಸ -',
      'Boxes {count}': 'ಬಾಕ್ಸ್‌ಗಳು {count}',
      'View remediation': 'ಚಿಕಿತ್ಸೆ ನೋಡಿ',
      'Image': 'ಚಿತ್ರ',
      'Heatmap': 'ಹೀಟ್‌ಮ್ಯಾಪ್',
      'Comparison': 'ಹೋಲಿಕೆ',
      'Captured': 'ಪಡೆಯಲಾಗಿದೆ',
      'Reference': 'ಉಲ್ಲೇಖ',
      'Remediation guide': 'ಚಿಕಿತ್ಸೆ ಮಾರ್ಗದರ್ಶಿ',
      'Remediation data unavailable.': 'ಚಿಕಿತ್ಸೆ ಡೇಟಾ ಲಭ್ಯವಿಲ್ಲ.',
      'No remediation found for {name}.': '{name} ಗೆ ಚಿಕಿತ್ಸೆಯಿಲ್ಲ.',
      'No treatment needed': 'ಚಿಕಿತ್ಸೆ ಅಗತ್ಯವಿಲ್ಲ',
      'Severity guidance': 'ತೀವ್ರತೆ ಮಾರ್ಗದರ್ಶನ',
      'Affected parts': 'ಪ್ರಭಾವಿತ ಭಾಗಗಳು',
      'Environmental risk factors': 'ಪರಿಸರ ಅಪಾಯ ಅಂಶಗಳು',
      'Organic treatment': 'ಜೈವಿಕ ಚಿಕಿತ್ಸೆ',
      'Chemical treatment': 'ರಾಸಾಯನಿಕ ಚಿಕಿತ್ಸೆ',
      'Prevention tips': 'ತಡೆಗಟ್ಟುವ ಸಲಹೆಗಳು',
      'Keep plants resilient with these steps.':
          'ಈ ಹೆಜ್ಜೆಗಳಿಂದ ಬೆಳೆಗಳನ್ನು ಬಲಪಡಿಸಿ.',
      'Community tips': 'ಸಮುದಾಯ ಸಲಹೆಗಳು',
      'Verified': 'ಪರಿಶೀಲಿತ',
      'Tips from experienced farmers': 'ಅನುಭವಿ ರೈತರಿಂದ ಸಲಹೆಗಳು',
      'Companion plants': 'ಸಹಾಯಕ ಸಸ್ಯಗಳು',
      'Plant these nearby for natural protection':
          'ನೈಸರ್ಗಿಕ ಸುರಕ್ಷೆಗಾಗಿ ಇವುಗಳನ್ನು ಬಳಿಯಲ್ಲಿ ನೆಡಿ',
      'When to seek expert': 'ತಜ್ಞರನ್ನು ಯಾವಾಗ ಸಂಪರ್ಕಿಸುವುದು',
      'Expected results': 'ನಿರೀಕ್ಷಿತ ಫಲಿತಾಂಶಗಳು',
      'Safety warnings': 'ಭದ್ರತಾ ಎಚ್ಚರಿಕೆಗಳು',
      'Dosage {value}': 'ಮಾತ್ರೆ {value}',
      'Frequency {value}': 'ಆವೃತ್ತಿ {value}',
      'Cost {value}': 'ವೆಚ್ಚ {value}',
      'Crop image': 'ಚಿತ್ರವನ್ನು ಕ್ರಾಪ್ ಮಾಡಿ',
      'The AI could not identify this disease with certainty. Please consult an agricultural expert for an accurate diagnosis.':
          'AI ಈ ರೋಗವನ್ನು ಖಚಿತವಾಗಿ ಗುರುತಿಸಲು ಸಾಧ್ಯವಾಗಲಿಲ್ಲ. ನಿಖರ ನಿರ್ಣಯಕ್ಕಾಗಿ ಕೃಷಿ ತಜ್ಞರನ್ನು ಸಂಪರ್ಕಿಸಿ.',
      
      // Chatbot strings
      'AI Assistant': 'AI ಸಹಾಯಕ',
      'AI Farm Assistant': 'AI ಕೃಷಿ ಸಹಾಯಕ',
      'Type your message...': 'ನಿಮ್ಮ ಸಂದೇಶವನ್ನು ಟೈಪ್ ಮಾಡಿ...',
      'Chat history cleared': 'ಚಾಟ್ ಇತಿಹಾಸ ತೆರವುಗೊಳಿಸಲಾಗಿದೆ',
      'Failed to clear chat history': 'ಚಾಟ್ ಇತಿಹಾಸ ತೆರವುಗೊಳಿಸುವಲ್ಲಿ ವಿಫಲವಾಗಿದೆ',
      'Clear chat': 'ಚಾಟ್ ತೆರವುಗೊಳಿಸಿ',
      'Sorry, I\'m having trouble right now. Please try again later.':
          'ಕ್ಷಮಿಸಿ, ನನಗೆ ಇದೀಗ ತೊಂದರೆಯಾಗುತ್ತಿದೆ. ದಯವಿಟ್ಟು ನಂತರ ಮತ್ತೆ ಪ್ರಯತ್ನಿಸಿ.',
    },
    'ml': {
      'AgroScan': 'AgroScan',
      'Sign in': 'സൈൻ ഇൻ',
      'Sign in to continue': 'തുടരാൻ സൈൻ ഇൻ ചെയ്യുക',
      'Email': 'ഇമെയിൽ',
      'Password': 'പാസ്വേഡ്',
      'Password is required.': 'പാസ്വേഡ് ആവശ്യമാണ്.',
      'Password must be at least 6 characters.':
          'പാസ്വേഡ് കുറഞ്ഞത് 6 അക്ഷരങ്ങൾ വേണം.',
      'Login': 'ലോഗിൻ',
      'Forgot password?': 'പാസ്വേഡ് മറന്നോ?',
      'New here?': 'പുതിയവരാണോ?',
      'Create account': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
      'Login successful.': 'ലോഗിൻ വിജയകരമായി.',
      'Create account title': 'അക്കൗണ്ട് സൃഷ്ടിക്കുക',
      'Join the community': 'സമുദായത്തിൽ ചേർക്കുക',
      'GPS helps personalize your reports':
          'GPS നിങ്ങളുടെ റിപ്പോർട്ടുകൾ വ്യക്തിഗതമാക്കാൻ സഹായിക്കുന്നു',
      'Full name': 'പൂർണ്ണനാമം',
      'Name is required.': 'പേര് ആവശ്യമാണ്.',
      'Email is required.': 'ഇമെയിൽ ആവശ്യമാണ്.',
      'Code': 'കോഡ്',
      'Phone': 'ഫോൺ',
      'Phone is required.': 'ഫോൺ ആവശ്യമാണ്.',
      'Preferred language': 'ഇഷ്ടമുള്ള ഭാഷ',
      'Address': 'വിലാസം',
      'Address is required.': 'വിലാസം ആവശ്യമാണ്.',
      'Register': 'രജിസ്റ്റർ',
      'Registration complete.': 'രജിസ്ട്രേഷൻ പൂർത്തിയായി.',
      'Location will be captured automatically.':
          'സ്ഥാനം സ്വയമേവ പിടിച്ചെടുക്കും.',
      'Location: {lat}, {lng}': 'സ്ഥാനം: {lat}, {lng}',
      'Reset password': 'പാസ്വേഡ് റീസെറ്റ്',
      'Forgot your password?': 'പാസ്വേഡ് മറന്നോ?',
      'We will send a reset code': 'റീസെറ്റ് കോഡ് അയക്കുന്നതാണ്',
      'Email or phone': 'ഇമെയിൽ അല്ലെങ്കിൽ ഫോൺ',
      'Email or phone is required.': 'ഇമെയിൽ അല്ലെങ്കിൽ ഫോൺ ആവശ്യമാണ്.',
      'Send reset code': 'റീസെറ്റ് കോഡ് അയയ്ക്കുക',
      'Enter the OTP sent to your email.':
          'നിങ്ങളുടെ ഇമെയിലിലേക്ക് അയച്ച OTP നൽകുക.',
      'OTP': 'OTP',
      'OTP is required.': 'OTP ആവശ്യമാണ്.',
      'New password': 'പുതിയ പാസ്വേഡ്',
      'New password is required.': 'പുതിയ പാസ്വേഡ് ആവശ്യമാണ്.',
      'Reset password button': 'പാസ്വേഡ് റീസെറ്റ്',
      'If the account exists, a reset code will be sent.':
          'അക്കൗണ്ട് ഉണ്ടായാൽ, റീസെറ്റ് കോഡ് അയക്കും.',
      'Password reset successful. You can log in now.':
          'പാസ്വേഡ് റീസെറ്റ് വിജയകരമായി. ഇപ്പോൾ ലോഗിൻ ചെയ്യാം.',
      'Profile': 'പ്രൊഫൈൽ',
      'Personal details': 'വ്യക്തിഗത വിവരങ്ങൾ',
      'Name': 'പേര്',
      'Location will be updated using GPS when you save.':
          'സേവ് ചെയ്യുമ്പോൾ GPS വഴി സ്ഥാനം പുതുക്കും.',
      'Update profile': 'പ്രൊഫൈൽ പുതുക്കുക',
      'Profile updated.': 'പ്രൊഫൈൽ പുതുക്കി.',
      'Missing access token.': 'ആക്സസ് ടോക്കൺ ഇല്ല.',
      'Field dashboard': 'ഫീൽഡ് ഡാഷ്ബോർഡ്',
      'Refresh': 'റിഫ്രെഷ്',
      'Notifications': 'അറിയിപ്പുകൾ',
      'Online': 'ഓൺലൈൻ',
      'Offline': 'ഓഫ്‌ലൈൻ',
      'Profile menu': 'പ്രൊഫൈൽ',
      'Logout': 'ലോഗ് ഔട്ട്',
      'Welcome, {name}': 'സ്വാഗതം, {name}',
      'Current weather': 'നിലവിലെ കാലാവസ്ഥ',
      'Live conditions near your farm': 'നിങ്ങളുടെ വയൽ സമീപം നിലകൾ',
      'Weather data unavailable.': 'കാലാവസ്ഥ ഡാറ്റ ലഭ്യമല്ല.',
      'Feels {value} C': 'തോന്നുന്നു {value} C',
      'Humidity {value}%': 'ആർദ്രത {value}%',
      'Wind {value} kph': 'കാറ്റ് {value} kph',
      'History analytics': 'ചരിത്ര വിശകലനം',
      'Trends from your recent scans': 'ഇടയ്ക്ക് സ്കാൻ ചെയ്തവയിലെ പ്രവണതകൾ',
      'Analytics data unavailable.': 'വിശകലന ഡാറ്റ ലഭ്യമല്ല.',
      'History records': 'ചരിത്ര രേഖകൾ',
      'Download or remove past reports':
          'മുൻ റിപ്പോർട്ടുകൾ ഡൗൺലോഡ് ചെയ്യുക അല്ലെങ്കിൽ നീക്കം ചെയ്യുക',
      'Filter by crop': 'വിള പ്രകാരം ഫിൽറ്റർ ചെയ്യുക',
      'All crops': 'എല്ലാ വിളകളും',
      'No history yet.': 'ഇതുവരെ ചരിത്രമില്ല.',
      'Scan crop': 'വിള സ്കാൻ ചെയ്യുക',
      'Total diagnoses': 'മൊത്തം നിർണയങ്ങൾ',
      'Low': 'കുറവ്',
      'Medium': 'മിതം',
      'High': 'ഉയരം',
      'Healthy': 'ആരോഗ്യം',
      'Crop: {crop}': 'വിള: {crop}',
      'Date: {date}': 'തീയതി: {date}',
      'Unknown crop': 'അജ്ഞാത വിള',
      'Report': 'റിപ്പോർട്ട്',
      'Report saved: {path}': 'റിപ്പോർട്ട് സേവ് ചെയ്തു: {path}',
      'Delete': 'ഇല്ലാതാക്കുക',
      'No notifications yet.': 'ഇതുവരെ അറിയിപ്പുകളില്ല.',
      'Notifications unavailable.': 'അറിയിപ്പുകൾ ലഭ്യമല്ല.',
      'Please log in to view notifications.':
          'അറിയിപ്പുകൾ കാണാൻ ലോഗിൻ ചെയ്യുക.',
      'Notification': 'അറിയിപ്പ്',
      'NEW': 'പുതിയത്',
      'Choose crop': 'വിള തിരഞ്ഞെടുക്കുക',
      'Gallery image': 'ഗാലറി ചിത്രം',
      'Gallery video': 'ഗാലറി വീഡിയോ',
      'Camera image': 'ക്യാമറ ചിത്രം',
      'Camera video': 'ക്യാമറ വീഡിയോ',
      'Unable to extract a frame from video.':
          'വീഡിയോയിൽ നിന്ന് ഫ്രെയിം എടുക്കാനായില്ല.',
      'Image is blurry': 'ചിത്രം മങ്ങലാണ്',
      'Please retake the image for a clearer result.':
          'കൂടുതൽ വ്യക്തമായ ഫലത്തിനായി ചിത്രം വീണ്ടും എടുക്കുക.',
      'OK': 'ശരി',
      'Missing access token. Please log in again.':
          'ആക്സസ് ടോക്കൺ ഇല്ല. വീണ്ടും ലോഗിൻ ചെയ്യുക.',
      'Diagnosis result': 'നിർണയ ഫലം',
      'Unknown disease': 'അജ്ഞാത രോഗം',
      'Confidence {value}%': 'വിശ്വാസം {value}%',
      'Confidence -': 'വിശ്വാസം -',
      'Boxes {count}': 'ബോക്സുകൾ {count}',
      'View remediation': 'ചികിത്സ കാണുക',
      'Image': 'ചിത്രം',
      'Heatmap': 'ഹീറ്റ്‌മാപ്പ്',
      'Comparison': 'താരതമ്യം',
      'Captured': 'പിടിച്ചത്',
      'Reference': 'റഫറൻസ്',
      'Remediation guide': 'ചികിത്സാ മാർഗ്ഗനിർദേശം',
      'Remediation data unavailable.': 'ചികിത്സ ഡാറ്റ ലഭ്യമല്ല.',
      'No remediation found for {name}.': '{name}ക്ക് ചികിത്സ ലഭ്യമല്ല.',
      'No treatment needed': 'ചികിത്സ ആവശ്യമില്ല',
      'Severity guidance': 'തീവ്രത മാർഗ്ഗനിർദേശം',
      'Affected parts': 'ബാധിക്കപ്പെട്ട ഭാഗങ്ങൾ',
      'Environmental risk factors': 'പരിസ്ഥിതി അപായ ഘടകങ്ങൾ',
      'Organic treatment': 'ജൈവ ചികിത്സ',
      'Chemical treatment': 'രാസ ചികിത്സ',
      'Prevention tips': 'തടയൽ നിർദ്ദേശങ്ങൾ',
      'Keep plants resilient with these steps.':
          'ഈ ഘട്ടങ്ങൾ കൊണ്ട് വിളകൾ ശക്തമാക്കുക.',
      'Community tips': 'സമുദായ നുറുങ്ങുകൾ',
      'Verified': 'പരിശോധിത',
      'Tips from experienced farmers':
          'അനുഭവസമ്പന്ന കർഷകരിൽ നിന്നുള്ള നുറുങ്ങുകൾ',
      'Companion plants': 'സഹജീവി സസ്യങ്ങൾ',
      'Plant these nearby for natural protection':
          'പ്രാകൃതിക സംരക്ഷണത്തിനായി ഇവ സമീപത്ത് നടുക',
      'When to seek expert': 'വിദഗ്ധരെ എപ്പോൾ സമീപിക്കണം',
      'Expected results': 'പ്രതീക്ഷിച്ച ഫലങ്ങൾ',
      'Safety warnings': 'സുരക്ഷാ മുന്നറിയിപ്പുകൾ',
      'Dosage {value}': 'മാത്രം {value}',
      'Frequency {value}': 'ആവർത്തനം {value}',
      'Cost {value}': 'ചെലവ് {value}',
      'Crop image': 'ചിത്രം ക്രോപ് ചെയ്യുക',
      'The AI could not identify this disease with certainty. Please consult an agricultural expert for an accurate diagnosis.':
          'AI ഈ രോഗം ഉറപ്പോടെ തിരിച്ചറിയാൻ കഴിഞ്ഞില്ല. കൃത്യമായ രോഗനിർണയത്തിനായി ഒരു കാർഷിക വിദഗ്ധനെ സമീപിക്കുക.',
      
      // Chatbot strings
      'AI Assistant': 'AI സഹായി',
      'AI Farm Assistant': 'AI കൃഷി സഹായി',
      'Type your message...': 'നിങ്ങളുടെ സന്ദേശം ടൈപ്പ് ചെയ്യുക...',
      'Chat history cleared': 'ചാറ്റ് ചരിത്രം മായ്ച്ചു',
      'Failed to clear chat history': 'ചാറ്റ് ചരിത്രം മായ്ക്കുന്നതിൽ പരാജയപ്പെട്ടു',
      'Clear chat': 'ചാറ്റ് മായ്ക്കുക',
      'Sorry, I\'m having trouble right now. Please try again later.':
          'ക്ഷമിക്കണം, എനിക്ക് ഇപ്പോൾ പ്രശ്നമുണ്ട്. ദയവായി പിന്നീട് വീണ്ടും ശ്രമിക്കുക.',
    },
  };

  static String t(
    String language,
    String key, {
    Map<String, String> args = const {},
  }) {
    final lang = _strings[language] ?? _strings[fallbackLanguage];
    var value = lang?[key] ?? _strings[fallbackLanguage]?[key] ?? key;

    args.forEach((placeholder, replacement) {
      value = value.replaceAll('{$placeholder}', replacement);
    });

    return value;
  }
}

extension LocalizationExtension on BuildContext {
  String t(String key, {Map<String, String> args = const {}}) {
    final language = watch<AppLanguage>().code;
    return AppLocalizations.t(language, key, args: args);
  }

  String tRead(String key, {Map<String, String> args = const {}}) {
    final language = read<AppLanguage>().code;
    return AppLocalizations.t(language, key, args: args);
  }
}
